const languages = {
    'zh-CN': {
        title: '券商费率对比计算器',
        hkTab: '港股',
        usTab: '美股',
        transactionValueLabel: '输入交易值（港元）',
        transactionValuePlaceholder: '请输入交易金额',
        orderCountLabel: '每月交易笔数',
        orderCountPlaceholder: '请输入每月交易笔数',
        platformModeLabel: '平台费模式',
        usTransactionValueLabel: '输入交易值（美元）',
        usTransactionValuePlaceholder: '请输入交易金额',
        usShareCountLabel: '交易股数',
        usShareCountPlaceholder: '请输入交易股数',
        usPlatformModeLabel: '美股平台费模式',
        usTradingActivityFee: '交易活动费',
        calculateButton: '计算费用',
        comingSoon: '开发中，尽情期待...',
        moreBrokers: '更多券商支持中...',
        bestPrice: '最优惠',
        // 费用项目
        commission: '佣金',
        platformFee: '平台费',
        agencyServiceFee: '代理服务费用',
        collectedFee: '代收费用',
        transactionFee: '交易费',
        stampDuty: '印花税',
        usExternalFee: '外部机构费及交易活动费',
        usAuditFee: '综合审计追踪费',
        sfcLevy: '证监会征费',
        frcLevy: '财务汇报局征费',
        settlementFee: '结算费',
        totalFee: '总费用',
        // 富途美股新增费用
        usSECRegulatoryFee: '证监会规费',
        usCATFee: '综合审计追踪费',
        // 平台费模式
        fixedMode: '固定式',
        steppedMode: '阶梯式',
        // 错误提示
        invalidInput: '请输入有效的正交易值！'
    },
    'en-US': {
        title: 'Broker Fee Comparison Calculator',
        hkTab: 'HK Stocks',
        usTab: 'US Stocks',
        transactionValueLabel: 'Transaction Value (HKD)',
        transactionValuePlaceholder: 'Enter transaction amount',
        orderCountLabel: 'Monthly Orders',
        orderCountPlaceholder: 'Enter monthly order count',
        platformModeLabel: 'Platform Fee Mode',
        usTransactionValueLabel: 'Transaction Value (USD)',
        usTransactionValuePlaceholder: 'Enter transaction amount',
        usShareCountLabel: 'Shares Traded',
        usShareCountPlaceholder: 'Enter number of shares',
        usPlatformModeLabel: 'US Platform Fee Mode',
        usTradingActivityFee: 'Trading Activity Fee',
        calculateButton: 'Calculate Fees',
        comingSoon: 'Coming Soon...',
        moreBrokers: 'More brokers support is coming soon...',
        bestPrice: 'Best Price',
        // Fee items
        commission: 'Commission',
        platformFee: 'Platform Fee',
        agencyServiceFee: 'Agency Service Fee',
        collectedFee: 'Collected Fee',
        transactionFee: 'Transaction Fee',
        stampDuty: 'Stamp Duty',
        usExternalFee: 'External Agency & Trading Activity Fee',
        usAuditFee: 'Consolidated Audit Trail Fee',
        sfcLevy: 'SFC Levy',
        frcLevy: 'FRC Levy',
        settlementFee: 'Settlement Fee',
        totalFee: 'Total Fee',
        // Futu US new fees
        usSECRegulatoryFee: 'SEC Regulatory Fee',
        usCATFee: 'Consolidated Audit Trail Fee',
        // Platform fee modes
        fixedMode: 'Fixed',
        steppedMode: 'Stepped',
        // Error messages
        invalidInput: 'Please enter a valid positive transaction value!'
    }
}; 